# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Build for distributing app using Firebase App Distributions"
   lane :distribute do
          gradle(task: "clean assembleRelease")
          firebase_app_distribution(
              app: '1:217238190087:android:c4a715c215aeebdb2452a2',
              firebase_cli_token: '1//03NQayruiHhUyCgYIARAAGAMSNwF-L9IrcdpsdEMuiQEEUzUmE84a2nToZkAyRFdx5CmJKnfewISHOGvuoL3aMT05hztt-G_Kuhw',
              groups: "testers",
              release_notes: "this message about finishing of fastlane implementation"
          )
   end
end
